framework:
    workflows:
        announce:
            type: 'workflow'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'state'
            supports:
                - App\Entity\Announce
            initial_marking: redaction
            places:
                - redaction
                - online
                - archived
            transitions:
                to_online:
                    from: redaction
                    to: online
                to_archived:
                    from: online
                    to: archived
